[package]
name = "ctypes-rust"
version = "0.0.0"
edition = "2024"

[workspace]
members = ["ctypes-endian", "ctypes-primitive"]

[dependencies]
derive_more = { version = "*", features = ["full"] }
num-traits = "0.2"
ctypes-endian = { path = "ctypes-endian" }
ctypes-primitive = { path = "ctypes-primitive" }

[features]
arc = []
